name: isar_plus_flutter_libs
resolution: workspace
description: Isar Plus Core binaries for the Isar Plus Database. Needs to be included for Flutter apps.
version: 0.0.0-placeholder
repository: https://github.com/ahmtydn/isar
homepage: https://github.com/ahmtydn/isar

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  isar_plus: 0.0.0-placeholder

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_plus_flutter_libs
        pluginClass: IsarPlusFlutterLibsPlugin
      ios:
        pluginClass: IsarPlusFlutterLibsPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: IsarPlusFlutterLibsPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: IsarPlusFlutterLibsPlugin
      windows:
        pluginClass: IsarPlusFlutterLibsPlugin
      web:
